name: NUnit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  failure-handler:
      if: failure() # Execute only if last job failed
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = "🚨 Tests échoué";
            const body = `Échec de tests dans le repo **${context.repo.owner}/${context.repo.repo}**.
            
            **Branch:** \`${context.ref}\`
            **Commit:** \`${context.sha}\`
  
            [🔗 Cliquez ici pour accéder les logs de GitHub Actions](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})  
  
            Regardez les logs pour trouver et corriger le problème.`;
  
            const labels = ["build", "error"];
            
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels
            });
            console.log(`Issue crée: ${issue.data.html_url}`);
